version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: python:3.9-slim
    container_name: backend_app
    working_dir: /app
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    command: >
      sh -c "apt-get update &&
            apt-get install -y netcat-openbsd &&
            pip install --no-cache-dir -r requirements.txt &&
            python app.py"

  frontend:
    image: node:18
    container_name: frontend_app
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm install &&
            npm run dev -- --host"

  populate_db:
    image: python:3.9-slim
    container_name: populate_db
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - backend
    command: >
      sh -c "apt-get update &&
            apt-get install -y netcat-openbsd postgresql-client &&
            chmod +x ./populate_db.sh &&
            while ! nc -z backend_app 5002; do sleep 1; done &&
            ./populate_db.sh"

volumes:
  db_data:
